GET http://localhost:8080/v1/checkout
Accept: application/json

###

POST http://localhost:8080/v1/checkout
Accept: application/json
Content-Type: application/json

{
  "cartId": 2,
  "paymentDetailsId": 2,
  "date": "2020-12-20",
  "total": 5000,
  "contact": "alonso",
  "address": "alonso@gmail.com"

}

###########
DELETE http://localhost:8080/v1/checkout/5
Accept: application/json

###########


