##########
GET http://localhost:8080/v1/city
Accept: application/json

##########
POST http://localhost:8080/v1/city
Accept: application/json
Content-Type: application/json

{
  "cityName": "Potosi"
}


