##############
GET http://localhost:8080/v1/company
Accept: application/json

###########333

POST http://localhost:8080/v1/company
Accept: application/json
Content-Type: application/json

{
  "name": "Computadoras Perez",
  "direction": "Av. Uyustus N205",
  "phone": "25252525",
  "email": "perezs@gmail.com"
}