###########
GET http://localhost:8080/v1/company/2
Accept: application/json

###########

POST http://localhost:8080/v1/company
Accept: application/json
Content-Type: application/json

{
  "name": "Computadoras Perez",
  "direction": "Av. Uyustus N205",
  "phone": "25252525",

  "email": "comgonzales@gmail.com"
}


###########
DELETE http://localhost:8080/v1/company?companyId=1
Accept: application/json

