##########
POST http://localhost:8080/v1/privilege
Accept: application/json
Content-Type: application/json

{
  "privilegeName": "Admin"
}

##########
PATCH http://localhost:8080/v1/privilege/privilege_name
Accept: application/json
Content-Type: application/json

{
  "privilegeId": 1,
  "privilegeName": "Create account"
}