##########
GET http://localhost:8080/v1/sale
Accept: application/json

##########
POST http://localhost:8080/v1/sale
Accept: application/json
Content-Type: application/json

{
  "companyId": 1,
  "card":"4321 1234 1234 1234",
  "month": "Enero",
  "year": 2025,
  "securityCode": 123,
  "name": "Alonso Herrera",
  "phone": "12345678",
  "direction": "Los andes",
  "total": 1000
}

##########

###

