##########
GET http://localhost:8080/v1/sale
Accept: application/json

###########
GET http://localhost:8080/v1/sale/1
Accept: application/json

###########

##########
POST http://localhost:8080/v1/sale
Accept: application/json
Content-Type: application/json

{
  "companyId": 1,
  "card":"4321 1234 1234 1234",
  "month": "Enero",
  "year": 2025,
  "securityCode": 123,
  "name": "Alonso Herrera",
  "phone": "12345678",
  "direction": "Los andes",
  "total": 1000
}

##########
###########
PATCH http://localhost:8080/v1/sale
Accept: application/json
Content-Type: application/json

{
  "saleId": 1,
  "companyId": 1,
  "card":"1111 1234 1234 1234",
  "month": "mayo",
  "year": 2028,
  "securityCode": 789,
  "name": "Alonso Herrera",
  "phone": "12345678",
  "direction": "Los andes",
  "total": 1000
}

###########
DELETE http://localhost:8080/v1/sale/4
Accept: application/json

###
###

