GET http://localhost:8080/v1/user/1
Accept: application/json

###
POST http://localhost:8080/v1/user/create
Accept: application/json
Content-Type: application/json

{
  "firstName": "Juanito",
  "lastName": "Prueba",
  "username": "juanprueba",
  "password": "prueba",
  "companyId": 1,
  "city": 1,
  "phone": "77747774",
  "email": "jprueba@gmail.com",
  "birthday": "1997-08-15"
}

###
