#############
GET http://localhost:8080/v1/user
Accept: application/json

#############

GET http://localhost:8080/v1/user/2
Accept: application/json

#############
POST http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "firstName": "Prueba2",
  "lastName": "Prueba2",
  "username": "prueba2",
  "password": "prueba2",
  "companyId": 3,
  "cityId": 4,
  "phone": "77778899",
  "email": "prueba2@gmail.com",
  "birthday": "1990-10-10"
}

###
