GET http://localhost:8080/v1/user/10
Accept: application/json

###
POST http://localhost:8080/v1/user/create
Accept: application/json
Content-Type: application/json

{
  "firstName": "Prueba1",
  "lastName": "Prueba1",
  "username": "prueba1",
  "password": "prueba1",
  "companyId": 3,
  "cityId": 4,
  "phone": "77777799",
  "email": "prueba@gmail.com",
  "birthday": "2000-10-10"
}

###
